### ISSUE TITLE
Vynil plugin produces output even when nothing is playing.

### ISSUE THREAD

**Issue by apoorv569** [swh/lv2#19]
The `vynil` plugin is making noise with crackle even when all playback is stopped and all plugin parameters are set to default.

![2022-12-27_19-55](https://user-images.githubusercontent.com/53279454/209680705-179df4f0-e4d0-4896-97bd-023929b0b9c0.png)

The screenshot was taken when the playback was stopped in `Ardour`.

**Comment by swh** [comment]
Hi, this is what it's intended to do - it doesn't have a built-in wet/dry control, the minimum distortion you can add is equivalent to a modern LP in good condition.

If you need to switch between transparency and filtered you'd need to mix between an unfiltered track and the filtered one.

**Comment by apoorv569** [comment]
> Hi, this is what it's intended to do - it doesn't have a built-in wet/dry control, the minimum distortion you can add is equivalent to a modern LP in good condition.
> 
> If you need to switch between transparency and filtered you'd need to mix between an unfiltered track and the filtered one.

I see.  Thanks. I will close this now.
