### ISSUE TITLE
`cleanup` functions assume that `activate()` has been called

### ISSUE THREAD

**Issue by surfacepatterns** [swh/lv2#8]
Many of the routines in the plugins allocate memory in the `activate()` method that is freed in the `cleanup()` method.  If the `activate()` method is never called (say, because the plugin was instantiated, but never used), then the program that loaded the plugin will crash.

For example, in 'plugins/allpass-swh.lv2/plugin.xml', the activate() method allocates memory:

```
plugin_data->buffer = calloc(size, sizeof(float));
```

... which isn't cleaned up until `cleanup()` is called:

```
free(plugin_data->buffer);
```

Note that this strategy also causes the plugins to leak memory, as a plugin could be activated and deactivated multiple times before `cleanup()` is called.

One of the following should occur:

1.) The memory should be allocated when the instance is first created.
2.) The memory should be freed in the `deactivate()` method.
3.) The `cleanup()` method should check to make sure that memory was actually allocated before freeing that memory.

(1) and (2) are ideal.

**Comment by cbix** [comment]
@swh are you accepting patches or planning to fix this eventually?
